language: java
install: true
jdk:
- oraclejdk8
script:
- ''
- "./gradlew build"
- "./gradlew javadoc"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: LXLcprzoK8s49DTc01pnwirTB45DUGyuhoLO8O4eCP9kM7AbjoaREKXsUpjCIItjpIpmQCMVvKHMp0A0TjZI2ZHESCcDzPiiI2n8wEdr/QQdVW8LJqqLKl4nBRRKAzgCkRREy7eodwjGJJ7h7ZY7VTCEu+Uuw7gVvnk/VXco37VTI/zsUU8xTmX4P4tngTREFLhR88s6UsyzsnYgDHjxRd+vqH0XzdqADoQPgetf5ruFtPkCLXnNlDf1SC2cLO87Z9SV8VBjPKLWPzA8gXL1g0ay6jDgTKyexMRCsWBPAFdlmOaH3mTY15bpG7gufFmoNba0+rkfFOGwLkV51BOA2IfyiKWOfw7F4xi1nWcsDAVfJ1ORfWgcMsiWyKvOs6/Nx87935BsD9uvY4DpzzePMTj/JNxQ/VYCwGpcAISYKl4PAoYvkh3f0Nyc7fBlgqGt7EcHf+ybd1b5T/Vj4pnqnkrVoDeFGSL6NB/hhkN9w78a8/ALt3KVjCUR8LIbmM5SXYlUl0nd2kFTLw3ief3Yk81s1mXEhq+DlrZ3/r2j6hNAkmofMS342Vwcj60e1ri4/4sbPHOUFLaaTMVOXAx8tt+3nCbEWmfPwd3BGDMx/5x19yefNgoWHpislRUrHRwWGZuoznqOVx34pKUyCRwfn2lF1D5iec+lJNhGybGm95o=
  file: $TRAVIS_BUILD_DIR/builds/*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: yehan2002/CombatLoggerPlus
